FROM python:3.12-slim
WORKDIR /app

# кладём код внутрь образа
COPY . /app

# ставим анализаторы
RUN pip install --no-cache-dir ruff bandit

# по умолчанию просто shell (команды передадим в docker run)
CMD ["sh", "-lc", "ruff --version && bandit --version"]
